### ISSUE TITLE
Package Installation Issue

### ISSUE THREAD

**Issue by SmallNic** [rkit/ssm-export-cli#2]
Hi @rkit, thanks for merging in that PR of mine! I went to update the version of the package in our product and ran into some problems:

```
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /path/to/project/node_modules/ssm-export-cli/dist/cli.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/path/to/project/node_modules/ssm-export-cli/dist/cli.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

We compared package v1.0.2 to v1.0.1 and it looks like the `.vscode` and `.dist` directories were absent:
![image](https://user-images.githubusercontent.com/10606769/189746841-8e074c61-9d7d-4e8f-800a-2aa6162317f2.png)

We suspect that only the src was package/published and that running the build step and trying again would fix it.

**Comment by rkit** [comment]
Oh, sorry… Fixed.
